### ISSUE TITLE
SnmpSharpNet relation?

### ISSUE THREAD

**Issue by astrowalker** [luqq/snmp-net#7]
Is this library is related in any way with [SnmpSharpNet](https://www.snmpsharpnet.com/)? The name at least is exactly the same.

**Comment by luqq** [comment]
It's the same library. Only addition is support for netstandard 2.0

**Comment by astrowalker** [comment]
Thank you for the answer. In such case I would say it would be polite to mention this fact in README and also preserve original license (it is LGPL, not GPL).
